name: 'Run Boman-CLI'
description: 'A GitHub Action to run the boman-cli tool'
author: 'Madhavan <pentester.maddy@gmail.com>'
branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  action:
    description: 'The action to perform'
    required: true
    default: 'run'
  failbuild:
    description: 'Fail the build on error'
    required: false
    default: 'all'
  zap_session_script:
    description: 'Path to the ZAP session script'
    required: false
    default: ''
  config:
    description: 'Path to the config file'
    required: false
    default: ''
  boman_saas_url:
      description: 'URL of the Boman SaaS'
      required: false
      default: 'https://dashboard.boman.ai/v2'
  use-sudo:
    description: 'Whether to run the command with sudo'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Install boman-cli
      run: pip install boman-cli
      shell: bash

    - name: Build the command
      id: build-command
      run: |
        cmd="boman-cli -action ${{ inputs.action }}"
        if [ "${{ inputs.failbuild }}" = "true" ]; then
          cmd="$cmd -failbuild"
        fi
        if [ -n "${{ inputs.zap_session_script }}" ]; then
          cmd="$cmd -zap_session_script ${{ inputs.zap_session_script }}"
        fi
        if [ -n "${{ inputs.config }}" ]; then
          cmd="$cmd -config ${{ inputs.config }}"
        fi
        if [ -n "${{ inputs.boman_saas_url }}" ]; then
          cmd="$cmd -u ${{ inputs.boman_saas_url }}"
        fi
        echo "cmd=$cmd" >> $GITHUB_ENV
      shell: bash

    - name: Run boman-cli without sudo
      if: ${{ inputs.use-sudo != 'true' }}
      run: ${{ env.cmd }}
      shell: bash

    - name: Run boman-cli with sudo
      if: ${{ inputs.use-sudo == 'true' }}
      run: sudo ${{ env.cmd }}
      shell: bash

outputs:
  result:
    description: 'The result of the boman-cli command'
